// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using task2.models;

#nullable disable

namespace task2.Migrations
{
    [DbContext(typeof(TaskDB))]
    [Migration("20240709170811_init2")]
    partial class init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("task2.models.InvoiceDetails", b =>
                {
                    b.Property<int>("Linenumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Linenumber"));

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitNo")
                        .HasColumnType("int");

                    b.HasKey("Linenumber");

                    b.HasIndex("UnitNo")
                        .IsUnique();

                    b.ToTable("InvoicesDetails");
                });

            modelBuilder.Entity("task2.models.Unit", b =>
                {
                    b.Property<int>("unitNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("unitNO"));

                    b.Property<string>("unitName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("unitNO");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("task2.models.InvoiceDetails", b =>
                {
                    b.HasOne("task2.models.Unit", "Unit")
                        .WithOne("invoiceDetails")
                        .HasForeignKey("task2.models.InvoiceDetails", "UnitNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("task2.models.Unit", b =>
                {
                    b.Navigation("invoiceDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
